In [9]:
% Matrices
A = [1 2 3; 4 5 6]
B = [0 -2 -3; -4 -5 -5]


A =

     1     2     3
     4     5     6


B =

     0    -2    -3
    -4    -5    -5



In [12]:
% operations
A + B
A + 2 * B
C = [A, B]
D = [A; B]


ans =

     1     0     0
     0     0     1


ans =

     1    -2    -3
    -4    -5    -4


C =

     1     2     3     0    -2    -3
     4     5     6    -4    -5    -5


D =

     1     2     3
     4     5     6
     0    -2    -3
    -4    -5    -5



In [30]:
% get a subset of matrix
C(1:2, [1, 3])


ans =

     1     3
     4     6



In [31]:
% transpose
C'


ans =

     1     4
     2     5
     3     6
     0    -4
    -2    -5
    -3    -5



In [32]:
% 
C * C'


ans =

    27    57
    57   143



In [33]:
% zero, ones matrix
ones(3,3)
zeros(2,3)


ans =

     1     1     1
     1     1     1
     1     1     1


ans =

     0     0     0
     0     0     0



In [34]:
% identity matrix
eye(3)


ans =

     1     0     0
     0     1     0
     0     0     1



In [35]:
% diagonal matrix
diag([1 2 3])


ans =

     1     0     0
     0     2     0
     0     0     3



In [36]:
% extract diagonal vector of matrix
diag_vector = diag(eye(3))


diag_vector =

     1
     1
     1



In [37]:
% example task: given the matrix A, replace its left top corner submatrix of 2x2 by ones
A = [1 2 3; 4 5 6; 7 8 9]
A(1:2, 1:2) = ones(2,2)


A =

     1     2     3
     4     5     6
     7     8     9


A =

     1     1     3
     1     1     6
     7     8     9



In [43]:
A = diag(5:-1:1)


A =

     5     0     0     0     0
     0     4     0     0     0
     0     0     3     0     0
     0     0     0     2     0
     0     0     0     0     1



In [46]:
A([1,2,3],[1,3,5])


ans =

     5     0     0
     0     0     0
     0     3     0



In [55]:
% element by element operatios
u = [1 2 3];
v = [10 5 10/3];

u .* v

[1 2; 3 4] .* ones(2,2) 


ans =

    10    10    10


ans =

     1     2
     3     4



In [51]:
% solve Ax = b => A^(-1)*A*x = A(-1)*b => x = A(-1)*b
b = [3; 1; 2];
A = [2 3 0; 1 0 -2; 0 0 3]; % invertible matrix

x = inv(A) * b; % using inverse matrix

z = A \ b; % using backslash operator (more efficient)

[x z]


ans =

    2.3333    2.3333
   -0.5556   -0.5556
    0.6667    0.6667



In [57]:
A = [1 2 3; 4 5 6; 7 8 9];

% get the 1st column of A
A(:,1)

% the 2nd row
A(2,:)


ans =

     1
     4
     7


ans =

     4     5     6

