In [5]:
% set a non-verbose output
format compact

In [6]:
% scalar type (integer)
a = 3

a =
     3


In [7]:
% or another scalar type (double)
b = 3.1415

b =
    3.1415


In [11]:
% operations on scalars
a + b
a * 2
a / b
a ^ 2

ans =
    6.1415
ans =
     6
ans =
    0.9550
ans =
     9


In [74]:
% functions on scalars
sin(pi/6)
cos(pi/3)
tan(pi/2)

ans =
    0.5000
ans =
    0.5000
ans =
   1.6331e+16


In [39]:
% enable ratio format
format rat

1.5 + 4.25

% get back to the short format
format short

ans =
      23/4     


In [15]:
% column vector
column_vector = [1;2;3;4;5]

column_vector =
     1
     2
     3
     4
     5


In [16]:
% row vector
row_vector = [1 2 3 4 5]

row_vector =
     1     2     3     4     5


In [40]:
% or with commas
row_vector = [1,2,3,4,5]

row_vector =
     1     2     3     4     5


In [43]:
% get the size of vector: rows and columns
size(row_vector)
size(column_vector)

ans =
     1     5
ans =
     5     1


In [20]:
% another way of creating a vector in some range
row_vector = [1:5]

row_vector =
     1     2     3     4     5


In [66]:
% with step 2
row_vector = [-5:2:5]

row_vector =
    -5    -3    -1     1     3     5


In [32]:
% 5 equally distributed elements in 1 .. 10
c = linspace(1, 10, 5)

c =
    1.0000    3.2500    5.5000    7.7500   10.0000


In [48]:
% concatenation of vectors
a = [1:2:10]
b = [2:2:10]

% concat into one-row vector
[a, b]

% concat into two-row vector
[a; b]

a =
     1     3     5     7     9
b =
     2     4     6     8    10
ans =
     1     3     5     7     9     2     4     6     8    10
ans =
     1     3     5     7     9
     2     4     6     8    10


In [56]:
% access elements of vector
a(2) % one element
a(1:2) % a slice from 1st to 2nd (inclusive)
a([1, 3, 5]) % a subset of vector (1st, 3rd, and 5th elements)

ans =
     3
ans =
     1     3
ans =
     1     5     9


In [61]:
% transpose a row vector into column one
v = [1 2 3];
v'

% and vice-versa
v = [1; 2; 3; 4; 5];
v'

ans =
     1
     2
     3
ans =
     1     2     3     4     5


In [71]:
% sum of vectors
a = [1; 2; 3];
b = [-1; -2; -3];

sum = a + b

transposed = a * b' % b is transposed

multiply_by_scalar = a * 3

sum =
     0
     0
     0
transposed =
    -1    -2    -3
    -2    -4    -6
    -3    -6    -9
multiply_by_scalar =
     3
     6
     9


In [78]:
% zero vector
zero_row_vector = zeros(1,5)

% or
zero_column_vector = zeros(3, 1)

% vector with ones
ones_vector = ones(1, 3)

zero_row_vector =
     0     0     0     0     0
zero_column_vector =
     0
     0
     0
ones_vector =
     1     1     1
